# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180227_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
